## A super fast brush-up of `F#`
A just enough F# refresher for those among us who are totally new to the language

### Arrays 

In [ ]:
//Creating an integer array with some random integers
let xs = [|23;344;1;3;45;65|]


In [ ]:
//Static type in action
//Try changing the Array.filter to List.filer and see what happens
//Can you explain why ?
xs |> Array.filter (fun t -> t % 5 = 0)

### Lists


In [ ]:
//Creating an integer list with some random numbers
let xs_list = [3;5;4;25]


### Accessing array and List items by indexing

In [ ]:
//Accessing array and List element
printfn "second element in xs is %d" xs.[1]
printfn "second element in xs_list is %d" xs_list.[1]

### Defining a function 

In [ ]:
//Defining and calling a function
let Add2AndSquare x = (x + 2.) ** 2. 
Add2AndSquare 3.

### The Pipe 

In [ ]:
![](img\\fsharp-pipe-i-love.jpg)

### Recursive function definition using pattern matching

In [4]:
//Fibonacci number generation
let rec fib n = 
    match n with 
          | 1 -> 1
          | 0 -> 1
          | _ -> fib (n - 1 ) + fib (n - 2)

//calling the generator
[1 .. 11] |> List.map fib// ( fun t -> fib t)


[1; 2; 3; 5; 8; 13; 21; 34; 55; 89; 144]

### `map` Function

In [ ]:
[1 .. 10] |> List.map (fun t -> t + 1)

In [ ]:
//Defining a function
let sqr x = x * x


### Defining a function and using it with `map`

In [ ]:
sqr

In [ ]:
[1 .. 10] |> List.map (fun t -> (t , sqr t))

### `filter` function 

In [ ]:
//Just the even numbers
[1 .. 10] |> List.filter (fun t -> t % 2 = 0)

In [ ]:
//Passing a function to filter with 
let isEven x = x % 2 = 0
[1 .. 10] |> List.filter isEven

### `countBy` function

In [ ]:
let numbers =[[1 .. 5];[2 .. 7]]|> List.concat 
numbers

In [ ]:
numbers |> List.countBy (fun t -> t)
numbers |> List.countBy (fun t -> t % 2 = 0)

### Tuple 

In [ ]:
//Creation
let sudipta = ("Sudipta", 2016, "Roslyn")
//Destructuring 
let (name, year_of_joining, expertise ) = sudipta

In [ ]:
name

In [ ]:
year_of_joining 

In [ ]:
expertise

In [ ]:
sudipta

In [ ]:
let location = (34,24)

### Introducing `fst` and `snd` method to access Tuple attributes

In [ ]:
let x_axis = fst location
let y_axis = snd location
printfn "The location is %d km on X axis and %d km on Y axis" x_axis y_axis

In [ ]:
//Going nested 
let something = ("A",("B",(1,3)))
//getting "A"
printfn "%s" (fst something)
//getting "B"
printfn "%s" (fst (snd something))
//getting "1"
printfn "%d" (fst  (snd (snd something)))
//TODO for you 
//write expression to get to "3"
printfn "%d" 


### `sumBy` method

In [ ]:
[1 .. 10] |> List.sumBy (fun t -> sqrt (float t))

### `averageBy` method

In [ ]:
let givenPairs = [("A",12.);("B",21.);("C",32.);("D",20.)]
givenPairs |> List.averageBy snd

### `zip` method

![](https://media.tenor.com/images/92e5901ce15219d9d4b08aaff1d91a1a/tenor.gif)

In [ ]:
let xvals = [1 .. 10]

In [ ]:
let squares = xvals |> List.map sqr 

In [ ]:
let pairs = List.zip xvals squares

In [ ]:
pairs

In [ ]:
//names 
let names = ["John";"Mary";"Jennifer";"Nancy";"Jeorge"]
//salutations
let salutations = ["Mr."; "Mrs."; "Ms.";"Ms.";"Master." ]

printfn "%A" (List.zip salutations names)
let smithFamily = List.zip salutations names 

                  |> List.map 
                   (fun pair -> fst pair + " " + snd pair + " Smith")
                   
smithFamily |> List.iter (fun name -> printfn "%s" name)

### Casting

In [ ]:
//Casting integer to float 
let x = 10
printfn "%f " (float x)

In [ ]:
//casting float to integer 
let p = 3.14159
printfn "%d" (int p)

### Function application 

In [ ]:
let f x = x + 1
let g x = x + 2
let h x = x + 3
//Use brackets only to remove ambiguity 
//otherwise not required 
//applying f
let f_applied = f 4
printfn "%d" f_applied
let fog x = f (g x)
let hfog x  = h (f (g x))
printfn "%A" (hfog 4)

### Function composition 

In [ ]:
let fog2 = f >> g

In [ ]:
fog2 4

## Function Returing Tuples