## Recognizing Handwritten Digits

![](https://www.researchgate.net/profile/Amaury_Lendasse/publication/264273647/figure/fig1/AS:295970354024489@1447576239974/9-Sample-digits-of-MNIST-handwritten-digit-database.png)

## Step 1 : (Get the data)
Download the data from https://www.kaggle.com/ngbolin/mnist-dataset-digit-recognizer/data or from the github repo folder (Project_1_Digit_Recognizer)

## Step 2 : (Build the generic k-NN)

### Step 2(a) Create the type of row entry
One row from the training data (some of the columns are stripped for brevity) looks like this 

![](https://i.ibb.co/sCbmpZh/digits.png)

One row of this CSV can be represented by the following type 

In [7]:
/// [Represents a row in the training data for kNN]
type Entry = {Label : string; Values : float[]}

### Step 2(b) Create the distance function 

The following equation depicts the Euclidean Distance 
### $$d(p,q) = \sqrt{(p_1 - q_1)^2 + (p_2 - q_2)^2 + .... + (p_n - q_n) ^ 2)}$$

In [8]:
let distance (values1 : float[]) (values2 : float[]) =
    let v1Length = values1.Length
    let v2Length = values2.Length
    let minLen = min v1Length v2Length
    let v1s = values1 |> Seq.take minLen
    let v2s = values2 |> Seq.take minLen 
    Seq.zip v1s v2s |>Seq.map (fun pair ->  (fst pair - snd pair) ** 2.) |> Seq.sum  

In [3]:
distance [|1.;3.3;3.;4.35443|]  [|3.;1.5;2.;4.3|] 

8.242962625

In [2]:
let cityBlock (values1 : float[]) (values2 : float[]) =
    let absPair pair = abs (fst pair - snd pair)
    let v1Length = values1.Length
    let v2Length = values2.Length
    let minLen = min v1Length v2Length
    let v1s = values1 |> Seq.take minLen
    let v2s = values2 |> Seq.take minLen 
    Seq.zip v1s v2s |> Seq.map absPair |> Seq.sum
    //|>Seq.map (fun pair -> abs (fst pair - snd pair) ) |> Seq.sum  

### Step 2(c) Create the generic kNN implementation

In [10]:
let kNN (entries : Entry list) ( newEntry : string * float[]) k = 
    entries|> List.map (fun x -> (x.Label , distance x.Values (snd newEntry)))
           |> List.sortBy snd 
           |> List.take k 
           |> List.countBy fst 

In [6]:
kNN //Type inference in action. Note that we didn't mention type for the input 'k'.
//compiler automatically annotates with type integer 

<fun:it@1> : (FSharpList`1 -> (Tuple`2 -> (int -> FSharpList`1)))

In [ ]:
## k-NN Intution 


In [11]:
let kNNCity (entries : Entry list) ( newEntry : string * float[]) k = 
    entries|> List.map (fun x -> (x.Label , cityBlock x.Values (snd newEntry)))
           |> List.sortBy snd 
           |> List.take k 
           |> List.countBy fst 

In [12]:
cityBlock

<fun:it@1> : (Double[] -> (Double[] -> double))

### Step 2(d) Playing with kNN 

In [9]:
let entries = [{Label = "1"; Values =[|1.;3.3;3.;4.33443|]};{Label = "1"; Values =[|1.;3.3;3.03;4.33443|]}; 
               {Label = "11"; Values =[|11.;13.13;13.;14.33443|]}]

In [10]:
entries

[{Label = "1";
  Values = [|1.0; 3.3; 3.0; 4.33443|];}; {Label = "1";
                                          Values = [|1.0; 3.3; 3.03; 4.33443|];};
 {Label = "11";
  Values = [|11.0; 13.13; 13.0; 14.33443|];}]

In [11]:
let unknown = ("X",[|0.99;3.23;3.0;4.23443|])

In [12]:
unknown

("X", [|0.99; 3.23; 3.0; 4.23443|])

In [13]:
kNN entries unknown 3

[("1", 2); ("11", 1)]

In [13]:
open System.IO

In [14]:
let loadValues filename = 
    File.ReadAllLines filename 
    |> Seq.skip 1
    |> Seq.map (fun line -> 
        {
            Label = line.Substring(0,line.IndexOf(','));
            Values = line.Split(',') |> Seq.skip 1 |> Seq.map (fun n -> float n) |> Seq.toArray 
        })
    |> Seq.toList

In [15]:
let digits = loadValues @"C:\Personal2\train.csv"

In [17]:
digits

[{Label = "1";
  Values =
   [|0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0;
     0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0;
     0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0;
     0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0;
     0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0;
     0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0;
     0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; ...|];};
 {Label = "0";
  Values =
   [|0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0;
     0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0;
     0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0;
     0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0;
     0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0;
    

In [16]:
let X  =  digits.[0].Values

In [17]:
X

[|0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0;
  0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0;
  0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0;
  0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0;
  0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0;
  0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0;
  0.0; 0.0; 0.0; 0.0; ...|]

In [20]:
let drawDigit (X:float[]) = 
    let avg = X |> Array.average
    let max  = X |> Array.max 
    printfn "Max is %f" max
    for m in 0 .. 27 do
        for n in 0 .. 27 do 
            if X.[m*n] >= avg then //&& X.[m*n] <= max then
                printf "*  "//"%f" X.[m*n+1]
            else
                printf ".  "
        printfn ""

In [21]:
let newUnknown = ("X",[|0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;68.0;86.0;163.0;228.0;255.0;254.0;176.0;156.0;73.0;53.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;171.0;252.0;225.0;198.0;198.0;199.0;198.0;245.0;253.0;253.0;249.0;131.0;8.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;191.0;107.0;18.0;0.0;0.0;0.0;0.0;31.0;36.0;68.0;152.0;250.0;158.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;32.0;243.0;216.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;33.0;170.0;253.0;120.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;11.0;119.0;254.0;255.0;173.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;36.0;107.0;225.0;253.0;214.0;83.0;8.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;68.0;159.0;241.0;245.0;171.0;120.0;11.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;6.0;123.0;199.0;241.0;253.0;169.0;44.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;137.0;253.0;253.0;253.0;253.0;254.0;186.0;135.0;52.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;85.0;181.0;181.0;181.0;181.0;182.0;223.0;254.0;254.0;221.0;85.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;10.0;63.0;147.0;237.0;249.0;152.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;91.0;241.0;245.0;76.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;125.0;253.0;165.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;170.0;253.0;184.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;6.0;106.0;255.0;238.0;26.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;20.0;93.0;185.0;253.0;254.0;146.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;19.0;37.0;102.0;186.0;230.0;248.0;253.0;227.0;133.0;16.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;3.0;25.0;109.0;135.0;199.0;226.0;253.0;253.0;254.0;253.0;250.0;189.0;16.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;166.0;253.0;253.0;195.0;247.0;240.0;233.0;188.0;163.0;111.0;62.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0|])

In [22]:
kNN digits newUnknown 9

[("3", 9)]

In [23]:
drawDigit digits.[8].Values

Max is 255.000000
.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  
.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  
.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  
.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  
.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  
.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  
.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  *  .  
.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  *  *  .  .  *  *  
.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  *  .  .  *  .  .  *  *  
.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  *  .  .  *  *  .  *  *  .  *  .  
.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  *  .  *  *  .  *  .  .  .  .  .  .  
.  .  .  .  .  .  .  .  .  .  .  .  .  .  *  . 

In [23]:
let Transform2D (pArrayWidth:int) (pArray:float[]) = 
    let tHeight = 28 //pArray.Length / pArrayWidth
    let tImageArray = Array.zeroCreate<float[]> tHeight

    let mutable tStart = 0
    let mutable tFinish = tStart + pArrayWidth - 1        // 0 indexed array

    for tRowIndex in [ 0 .. tHeight ] do
        tImageArray.[tRowIndex] <- pArray.[tStart .. tFinish-1]
        tStart <- tStart + pArrayWidth
        tFinish <- tFinish + pArrayWidth
    
    tImageArray

In [26]:
digits.[3].Values

[|0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0;
  0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0;
  0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0;
  0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0;
  0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0;
  0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0;
  0.0; 0.0; 0.0; 0.0; ...|]

In [27]:
System.Drawing.Bitmap original = new System.Drawing.Bitmap (original.Width, original.Height);

        for (int j = 0; j < original.Height; j++)
        {
            for (int i = 0; i < original.Width; i++)
            {
                Color newColor = Color.FromArgb((int)grayScale[i + j * original.Width], (int)grayScale[i + j * original.Width], (int)grayScale[i + j * original.Width]);

                newBitmap.SetPixel(i, j, newColor);
            }
        }

        Image img = (Image)newBitmap;

Unexpected symbol '=' in pattern. Expected ')' or other token.
Unmatched '('
Unexpected symbol ';' in expression
Unexpected symbol ')' in expression
parse error

In [24]:
drawDigit digits.[3].Values

Max is 255.000000
.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  
.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  
.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  
.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  
.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  
.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  
.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  
.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  *  .  .  .  *  .  .  
.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  
.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  *  
.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  *  *  
.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . 

In [51]:
kNN digits ("X",digits.[3].Values) 3

[("4", 3)]

In [52]:
kNN digits ("X",digits.[08].Values) 3

[("5", 3)]

In [27]:
kNN digits ("X",digits.[09].Values) 3

[("3", 3)]

In [28]:
digits.[09].Label

"3"

In [29]:
kNN

<fun:it@1-3> : (FSharpList`1 -> (Tuple`2 -> (int -> FSharpList`1)))

In [30]:
#time "on"
[1 .. 10] |> List.map (fun t -> ("Actual = " + digits.[t].Label, 
                                 "Guessed = " + fst (kNN digits ("X",digits.[t].Values) 5).[0]))

[("Actual = 0", "Guessed = 0"); ("Actual = 1", "Guessed = 1");
 ("Actual = 4", "Guessed = 4"); ("Actual = 0", "Guessed = 0");
 ("Actual = 0", "Guessed = 0"); ("Actual = 7", "Guessed = 7");
 ("Actual = 3", "Guessed = 3"); ("Actual = 5", "Guessed = 5");
 ("Actual = 3", "Guessed = 3"); ("Actual = 8", "Guessed = 8")]

In [31]:
[1 .. 10] |> List.map (fun t -> ("Actual = " + digits.[t].Label, 
                                 "Guessed = " + fst (kNNCity digits ("X",digits.[t].Values) 5).[0]))

[("Actual = 0", "Guessed = 0"); ("Actual = 1", "Guessed = 1");
 ("Actual = 4", "Guessed = 4"); ("Actual = 0", "Guessed = 0");
 ("Actual = 0", "Guessed = 0"); ("Actual = 7", "Guessed = 7");
 ("Actual = 3", "Guessed = 3"); ("Actual = 5", "Guessed = 5");
 ("Actual = 3", "Guessed = 3"); ("Actual = 8", "Guessed = 8")]

In [32]:
#time "on"
[1 .. 10]
#time "off"

[1; 2; 3; 4; 5; 6; 7; 8; 9; 10]

In [33]:
digits.[1 .. 5]

[{Label = "0";
  Values =
   [|0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0;
     0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0;
     0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0;
     0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0;
     0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0;
     0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0;
     0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; ...|];};
 {Label = "1";
  Values =
   [|0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0;
     0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0;
     0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0;
     0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0;
     0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0;
    

In [34]:
snd sam

The value or constructor 'sam' is not defined.

In [35]:
[1 .. 10]

[1; 2; 3; 4; 5; 6; 7; 8; 9; 10]

In [36]:
kNNCity digits ("X",digits.[10].Values) 5

[("8", 5)]

In [37]:
let w = new System.Diagnostics.Stopwatch ()
w.Start()
let guesses = kNNCity (digits|>List.take 5000) ("X",digits.[10].Values) 5
printfn "Actual %s Classified %s" digits.[10].Label (fst guesses.[0])
w.Stop()
printfn "%d" w.ElapsedMilliseconds
#time

Actual 8 Classified 8
678


In [38]:
let timer = new System.Diagnostics.Stopwatch ()
timer.Start()
let trimmed = digits |> List.take 500
//let result  = [1 .. 50] |> List.map (fun t -> ("Actual = " + digits.[t].Label, 
                                           //    "Guessed = " + fst (kNN trimmed ("X",digits.[t].Values) 5).[0]))
let result2  = [1 .. 500] |> List.map (fun t -> (digits.[t].Label, 
                                                   (fst (kNN trimmed ("X",digits.[t].Values) 5).[0])))
let failed = result2 |> List.filter(fun pair -> fst pair <> snd pair) |> List.length
printfn "%d failed out of 500" failed
//printfn "%A" result
timer.Stop()
printfn "Took %d" timer.ElapsedMilliseconds 

0 failed out of 500
Took 44288


### A hack to make k-NN  [color=red]super fast

In [39]:
let mappedList : ((int * int) list)list = []

In [48]:
//Tracing path of a digit 
digits.[0].Values 
  |> Array.mapi(fun index item -> (index,item))
  |> Array.filter(fun pair -> snd pair <> 0.0)
  |> Array.map (fun pair -> fst pair)

[|132; 133; 134; 159; 160; 161; 162; 186; 187; 188; 189; 190; 213; 214; 215; 216;
  217; 240; 241; 242; 243; 244; 267; 268; 269; 270; 271; 294; 295; 296; 297; 298;
  299; 321; 322; 323; 324; 325; 348; 349; 350; 351; 352; 353; 376; 377; 378; 379;
  380; 403; 404; 405; 406; 407; 408; 431; 432; 433; 434; 435; 458; 459; 460; 461;
  462; 485; 486; 487; 488; 489; 513; 514; 515; 516; 540; 541; 542; 543; 544; 567;
  568; 569; 570; 571; 595; 596; 597; 598; 599; 623; 624; 625; 626; 627; 652; 653;
  654|]

In [49]:
let getTrace values = 
    values 
      |> Array.mapi(fun index item -> (index,item))
      //|> Array.filter(fun pair -> snd pair <> 0.0)
      |> Array.filter(fun pair -> snd pair > 100.0)
      |> Array.map (fun pair -> fst pair)

In [50]:
getTrace

<fun:it@1-17> : (Double[] -> Int32[])

In [ ]:
digits |>List.take 4 |> List.map(fun t -> (t.Label, getTrace t.Values))

In [ ]:
[1;3;4;1;3;4;2]|> List.countBy (fun t -> t)

In [3]:
digits
   |> List.take 10 
   |> List.map(fun t -> (t.Label, getTrace t.Values)) 
   |> List.filter (fun pair -> fst pair = "1")       
   |> List.map snd
   |> Seq.concat
   |> Seq.countBy(fun index -> index)
   |> Seq.toList

The value or constructor 'digits' is not defined.
Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved.
The value or constructor 'getTrace' is not defined.

In [ ]:
let learnPaths (trainingDigits : Entry list) label = 
  trainingDigits
       |> List.map(fun t -> (t.Label, getTrace t.Values)) 
       |> List.filter (fun pair -> fst pair = label)       
       |> List.map(fun pair -> snd pair)
       |> Seq.concat
       |> Seq.countBy(fun index -> index)
       |> Seq.sortByDescending snd
       |> Seq.toList
    

In [ ]:
learnPaths

In [ ]:
let learnt = [0 .. 9] |> List.map (fun t -> t.ToString())
                      |> List.map (fun p -> (p , learnPaths  digits p))

In [ ]:
learnt.Length

In [ ]:
learnt

In [ ]:
[0 .. 9]

In [ ]:
learnt |> List.map(fun t -> (fst t, (snd t) |> List.length))

In [ ]:
digits.Length

In [ ]:
digits |> List.filter (fun t -> t.Label = "6")

In [ ]:
learnPaths digits "6"

In [ ]:
let firstMap = snd learnt.[0] |> Map.ofList

In [ ]:
firstMap.TryGetValue 6274

In [ ]:
snd (firstMap.TryGetValue 627)

In [ ]:
let initialGuess (learntModel : (string * (int * int)list) list) (unknown : float []) =
    //let touches = (snd unknown) |> Array.countBy (fun t -> t) 
    //touches
    unknown|> Array.mapi (fun index item -> if item <> 0.0 then index else - 1)
           |> Array.filter (fun t -> t <> -1)

In [ ]:
let guess_0 = initialGuess learnt (snd newUnknown)

In [ ]:
guess_0.Length

In [ ]:
learnt.Length

In [ ]:
let learntMap = learnt |> List.map (fun t -> (fst t, (snd t) |> Map.ofList)) 
                       |> Map.ofList

In [ ]:
learntMap

In [ ]:
learntMap.["8"].ContainsKey 32245435

In [ ]:
let argMapMax location  = 
    [0 .. 9] |> List.map( fun t -> t.ToString())
             |> List.map (fun t -> (t, learntMap.[t].TryGetValue location))
             |> List.filter (fun t -> snd (snd t) <> 0)
             |> List.map (fun t -> (fst t, float (snd(snd t))))
             |> List.sortByDescending snd

In [ ]:
argMapMax  627

In [ ]:
let initGuess location  =
    fst (argMapMax location ).[0]

In [ ]:
initGuess 406

In [ ]:
let guessFast (unknown : int[]) =
 let guesses = unknown        
                |> Array.mapi (fun index item -> if item <> 0 then index else -1)
                |> Array.filter (fun s -> s <> -1)
                |> Array.map (fun s -> initGuess s)
                |> Array.countBy  (fun z -> z)
                |> Array.sortByDescending snd 
 guesses.[0]              
                 

In [ ]:
guessFast

In [ ]:
let guessFastFlt (unknown : float[]) =
 let guesses = unknown        
                |> Array.mapi (fun index item -> if item <> 0.0 then index else -1)
                |> Array.filter (fun s -> s <> -1)
                |> Array.map (fun s -> initGuess s)
                |> Array.countBy  (fun z -> z)
                |> Array.sortByDescending snd 
 fst guesses.[0]   

In [1]:
let all_guesses (unknown : int[]) =
 let guesses = unknown        
                |> Array.mapi (fun index item -> if item <> 0 then index else -1)
                |> Array.filter (fun s -> s <> -1)
                |> Array.map (fun s -> initGuess s)
                |> Array.countBy  (fun z -> z)
                |> Array.sortByDescending snd 
 guesses   

The value or constructor 'initGuess' is not defined.

### Check line 20 in `train.csv`

In [ ]:
//This is indeed a 
all_gueses newUnknown

In [ ]:
let results = digits 
                |> List.take 600
                |> List.map (fun t -> (t.Label, guessFastFlt t.Values ))

In [ ]:
results |> List.filter (fun t -> fst t <> snd t) |> List.length

In [ ]:
results |> List.take 50

In [ ]:
digits |> List.countBy (fun t -> t.Label)